from flask import Flask, Response
from prometheus_client import Counter, generate_latest, CONTENT_TYPE_LATEST

app = Flask(__name__)

REQUEST_COUNT = Counter(
    "paved_road_http_requests_total",
    "Total HTTP requests received by the Paved Road test service",
    ["endpoint", "status"]
)

FAILURE_COUNT = Counter(
    "paved_road_failures_total",
    "Total intentional failures generated by the Paved Road test service"
)

HEALTH_COUNT = Counter(
    "paved_road_health_checks_total",
    "Total health check requests received by the Paved Road test service"
)


@app.route("/")
def fail():
    REQUEST_COUNT.labels(endpoint="/", status="500").inc()
    FAILURE_COUNT.inc()
    return "intentional failure\n", 500


@app.route("/health")
def health():
    REQUEST_COUNT.labels(endpoint="/health", status="200").inc()
    HEALTH_COUNT.inc()
    return "healthy\n", 200


@app.route("/metrics")
def metrics():
    return Response(generate_latest(), mimetype=CONTENT_TYPE_LATEST)


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080)