name: GCP Connection Test
on: 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-oidc:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2 # Explicitly using the latest patch

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2.1.8 # Updated version for Node 24 support
        with:
          workload_identity_provider: 'projects/915035381641/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'paved-road-sa@imposing-fx-413205.iam.gserviceaccount.com'

      - name: Verify Login
        run: |
          gcloud auth list
          gcloud projects describe imposing-fx-413205
