name: GCP Connection Test
on: 
  workflow_dispatch:

# Top-level environment variable to force the runner's hand
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

permissions:
  id-token: write
  contents: read

jobs:
  test-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/915035381641/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'paved-road-sa@imposing-fx-413205.iam.gserviceaccount.com'

      - name: Verify Login
        run: |
          gcloud auth list
          gcloud projects describe imposing-fx-413205
