name: Terraform Deploy

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: imposing-fx-413205
  REGION: us-central1
  TF_WORKING_DIR: terraform/environments/dev/cloud-run
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  terraform-deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Authenticate to GCP (OIDC)
        uses: google-github-actions/auth@v2.1.8
        with:
          workload_identity_provider: projects/915035381641/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: paved-road-sa@imposing-fx-413205.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} init

      - name: Terraform Validate
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} validate

      - name: Terraform Plan
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} plan

      - name: Terraform Apply
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} apply -auto-approve
